name: 'Swagger Parser CLI'
description: 'Uses swagger parser CLI to allow validation of a definition'
inputs:
  inputSpec:
    description: 'file of the openapi definition'
    required: true

runs:
  using: "composite"
  steps:
    - id: java-version
      run: java -version
      shell: bash
    - name: Build Java
      if: steps.java-version == null
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
    - name: Download JAR
      run: curl -L "https://repository.sonatype.org/service/local/artifact/maven/content?r=central-proxy&g=io.swagger.parser.v3&a=swagger-parser-cli&e=jar&v=LATEST" -o swagger-parser-cli.jar
      shell: bash
    - name: Execute Jar
      run: java -jar ./swagger-parser-cli.jar ${{ inputs.inputSpec }}
      shell: bash