name: 'Swagger Parser CLI'
description: 'Uses swagger parser CLI to allow validation of a definition'
inputs:
  inputSpec:
    description: 'file of the openapi definition'
    required: true
  options:
    description: 'parser options'
    required: false
  logsPath:
    description: 'file of the logs messages or errors'
    required: true
  parserSpecPath:
    description: 'path where a file can be found with parsed definition'
    required: false
runs:
  using: "composite"
  steps:
    - id: java-version
      run: java -version 2>&1 | fgrep -i version | cut -d'"' -f2 | sed -e 's/^1\./1\%/' -e 's/\..*//' -e 's/%/./'
      shell: bash
    - name: Build Java
      if: steps.java-version == null || steps.java-version < 1.8
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
    - name: Download JAR
      run: curl -L "https://repository.sonatype.org/service/local/artifact/maven/content?r=central-proxy&g=io.swagger.parser.v3&a=swagger-parser-cli&e=jar&v=LATEST" -o swagger-parser-cli.jar
      shell: bash
    - id: execute
      name: Execute Jar
      run: java -jar swagger-parser-cli.jar -i ${{ inputs.inputSpec }} ${{ inputs.options }} -o ${{ inputs.parserSpecPath }} -l ${{ inputs.logsPath }}
      shell: bash