name: SwaggerParserCLI Test

on: [push]

jobs:
  validate_job:
    runs-on: ubuntu-latest
    name: A job to validate a definition
    steps:
      - uses: actions/checkout@v3
        with:
          ref: action
      - uses: ./.github/actions/
        with:
          inputSpec: 'modules/swagger-parser-cli/target/test-classes/fileWithValidationErrorMessages.yaml'
